name: Run Tests in Parallel
on: [push]
jobs:
  my-job:
    name: Run MATLAB unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up products
        uses: matlab-actions/setup-matlab@v2
        with:
          products: >
            Symbolic_Math_Toolbox
            Parallel_Computing_Toolbox
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          use-parallel: true
          source-folder: Matlab; Matlab/src; Matlab/src/normal_forms; Matlab/src/params; Matlab/src/rank_cases; Matlab/src/rank_cases_fp; Matlab/src/plots; Matlab/src/utils
